### ISSUE TITLE
Using linked module from the Wasmtime generated code results in missing `canonical_abi_free` export

### ISSUE THREAD

**Issue by radu-matei** [bytecodealliance/witx-bindgen#59]
The use case is the following: I am using the generated export Wasmtime bindings to execute a specific function through Wasmtime. This works fine for modules that have not been linked, but fails for modules that import any interfaces and need to be linked.

(First, the module must export a `_start` function. Adding a dummy `_start` bypasses this) 

The error I'm seeing: "failed to find function export `canonical_abi_free`".

The Wasmtime bindings explicitly try to use the free function (when using strings in the function signatures), and apparently the linked module does not re-export it.

A couple of questions:
- is there a reason to explicitly require the `_start` function before linking a module?
- is there a way to re-export the `canonical_abi_free` function (and I assume the same is valid for the `realloc` function)?

Thanks!

cc @peterhuene

**Comment by peterhuene** [comment]
Hi Radu.

There's no reason to require `_start` as an export from the "main" module; we should simply be re-exporting all exported functions, `_start` and `canonical_abi_*` included.

I'll get this fixed tomorrow.

**Comment by saona-raimundo** [comment]
Hi there!

First of all, thank you for the great work!! I was poking around and it looks fantastic!

About this issue, is there any reason why the `canonical_abi_*` (`realloc` and `free`) is not part of the current generated bindings? Say, to the result of a Rust-export.

If these functions are not supposed to be in any particular generated bindings (I assume because they would be part of some sort of "linker", to not have code repetition), where is this linker supposed to be?

## Comments

I know about the [`wasmlink`](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wasmlink) crate, but it seems that it would constrain the host to compile to `wasm`. Please correct me if I am wrong.

## Use case

I want an app written in Rust that uses `wasmtime-the-crate` to run wasm modules. These wasm modules implement the functions in some `.wit` file. The `.wit` file is like the "public plugin API": if you want my app to run your plugin, implement the functions in this `.wit` file.

When I tried to put this setup together, compiling some `.wasm` "plugin" was easy, thanks to `wit-bindgen` :).
When I tried to run the `wasm` through `wasmtime-the-crate` in my app, I needed wasi (okay, added to the linker) and also the [`canonical_abi_free` function](https://github.com/bytecodealliance/wit-bindgen/blob/main/crates/rust-wasm/src/lib.rs#L158). 

This was nowhere to be found, except as part of the `rust-wasm` crate.

## Easy-fix

Adding [`canonical_abi_free` function](https://github.com/bytecodealliance/wit-bindgen/blob/main/crates/rust-wasm/src/lib.rs#L158) to the generated bindings of Rust-export solved the issue. Now the wasm module that I will call has its own `canonical_abi_free` function, so it is available when I asked `wasmtime-the-crate` to run the functions defined in my `.wit`.

## On code repetition

If `canonical_abi_*` are added to every binding generated, there would lot of code repetition, right? All you need is this function once. But looking at the Wasmtime-import binding generated, it feels like these functions are meant to be exactly there: in the Rust-export code.

**Comment by alexcrichton** [comment]
Currently the various intrinsics are provided in Rust via the runtime crate itself. It's not intended that the `wit-bindgen` CLI tool is used literally per se for Rust, but rather the `wit-bindgen-{rust,wasmtime}` crates would be used with their procedural macros to get all the runtime support to line up. Does that work for you?

**Comment by saona-raimundo** [comment]
I am really sorry, I thought I had understood what was going on, but it seems I did not.

Using the macros in the `wit-bindgen-{rust,wasmtime}` crates works like a charm. I simply started again from the demo in `wasmlink` and it worked.

So... just for curiosity, in which step are the `canonical_abi_*` functions included?

<details>
  <summary>In case it is needed, this is my setup</summary>
  
See [full code here](https://github.com/saona-raimundo/wasm_renderer). 

# Overview

It is very similar to [wasmlink/demo](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wasmlink/demo). The difference is that the host application runs the `wasmtime` engine directly, so running the app is simply `cargo run`.

- There is a `.wit` file used by the host app and the "plugin" (markdown).
- The plugin uses `wit_bindgen_rust::export!("../renderer.wit");` to implement the "plugin API".
- The host app uses `wit_bindgen_wasmtime::import!("../renderer.wit");`.

# Host app details

This is how I set up a plugin, so that I can call the functions in the app.
```rust
use wasmtime::*;
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder};

wit_bindgen_wasmtime::import!("../renderer.wit");
use renderer::*;

fn setup() -> anyhow::Result<(
    Store<(WasiCtx, RendererData)>,
    Renderer<(WasiCtx, RendererData)>,
)> {
    // Setup wasmtime runtime
    let engine = Engine::default();
    let module = Module::from_file(&engine, "plugins/markdown.wasm")?;

    // Our instantiation is not trivial, as we use the `.wit` file,
    // so we need to use a Linker.
    let mut linker = Linker::new(&engine);
    // In the linker, we have to add support for Wasi, as it is used by the plugin.
    wasmtime_wasi::add_to_linker(&mut linker, |(wasi, _plugin_data)| wasi)?;
    // Create a Wasi context.
    let wasi = WasiCtxBuilder::new()
        .inherit_stdio()
        .inherit_args()?
        .build();
    // In our case, there is no host data we want the plugin to modify,
    // so we pass nothing, represented by: `app_public::PluginData`...
    // But we also have to pass the wasi context just created.
    let mut store = Store::new(&engine, (wasi, renderer::RendererData {}));

    let (plugin, _instance) =
        Renderer::instantiate(&mut store, &module, &mut linker, |(_wasi, plugin_data)| {
            plugin_data
        })?;

    Ok((store, plugin))
}
```
</details>

**Comment by alexcrichton** [comment]
When the `wit-bindgen-rust` crate is linked into the final wasm module it contains the canonical abi intrinsics, located [here](https://github.com/bytecodealliance/wit-bindgen/blob/d17f6734422a66ef945710c710e468cc1b0fbc56/crates/rust-wasm/src/lib.rs#L133-L164)

**Comment by saona-raimundo** [comment]
Perfect!

Now I know what happened now!

# Steps to reproduce what happened to me

- Replace the macro `wit_bindgen_rust::export!("../renderer.wit");` by its extension (say, from the cli) 
- Drop teh dependence `wit-bindgen-rust` from your Cargo.toml
- Build targeting `wasm32-wasi`

At the end, the generated `.wasm` does not contain the canonical abi intrinsics!

(Maybe it is obvious foru you from the beginning...)

# On code repetition

(I can start a new issue for this one, I am asking here just to know if it is worth it)
By design, the canonical abi intrinsics are packed into the wasm file that uses it. If there were many wasm modules, each of them will have the same canonical abi intrinsics. 

Would it not be better if the runtime is the one responsible to contain the canonical abi intrinsics?

This design already happens with wasi: one needs to link wasi to the the runtime. Wasi functions are not packed within every wasm module.

**Comment by alexcrichton** [comment]
For an issue about the definition of `canonical_abi_free` I'd recomend opening an issue at https://github.com/WebAssembly/interface-types

**Comment by nitishm** [comment]
> I am really sorry, I thought I had understood what was going on, but it seems I did not.
> 
> Using the macros in the `wit-bindgen-{rust,wasmtime}` crates works like a charm. I simply started again from the demo in `wasmlink` and it worked.
> 
> So... just for curiosity, in which step are the `canonical_abi_*` functions included?
> 
> In case it is needed, this is my setup
> See [full code here](https://github.com/saona-raimundo/wasm_renderer).
> 
> # Overview
> It is very similar to [wasmlink/demo](https://github.com/bytecodealliance/wit-bindgen/tree/main/crates/wasmlink/demo). The difference is that the host application runs the `wasmtime` engine directly, so running the app is simply `cargo run`.
> 
> * There is a `.wit` file used by the host app and the "plugin" (markdown).
> * The plugin uses `wit_bindgen_rust::export!("../renderer.wit");` to implement the "plugin API".
> * The host app uses `wit_bindgen_wasmtime::import!("../renderer.wit");`.
> 
> # Host app details
> This is how I set up a plugin, so that I can call the functions in the app.
> 
> ```rust
> use wasmtime::*;
> use wasmtime_wasi::{WasiCtx, WasiCtxBuilder};
> 
> wit_bindgen_wasmtime::import!("../renderer.wit");
> use renderer::*;
> 
> fn setup() -> anyhow::Result<(
>     Store<(WasiCtx, RendererData)>,
>     Renderer<(WasiCtx, RendererData)>,
> )> {
>     // Setup wasmtime runtime
>     let engine = Engine::default();
>     let module = Module::from_file(&engine, "plugins/markdown.wasm")?;
> 
>     // Our instantiation is not trivial, as we use the `.wit` file,
>     // so we need to use a Linker.
>     let mut linker = Linker::new(&engine);
>     // In the linker, we have to add support for Wasi, as it is used by the plugin.
>     wasmtime_wasi::add_to_linker(&mut linker, |(wasi, _plugin_data)| wasi)?;
>     // Create a Wasi context.
>     let wasi = WasiCtxBuilder::new()
>         .inherit_stdio()
>         .inherit_args()?
>         .build();
>     // In our case, there is no host data we want the plugin to modify,
>     // so we pass nothing, represented by: `app_public::PluginData`...
>     // But we also have to pass the wasi context just created.
>     let mut store = Store::new(&engine, (wasi, renderer::RendererData {}));
> 
>     let (plugin, _instance) =
>         Renderer::instantiate(&mut store, &module, &mut linker, |(_wasi, plugin_data)| {
>             plugin_data
>         })?;
> 
>     Ok((store, plugin))
> }
> ```

@alexcrichton it would be pretty helpful to have an example of wit-bindgen-wasmtime in the repo. I can add a simple hello-world (or markdown/rendered) example to an examples dir?

**Comment by alexcrichton** [comment]
I agree that examples would be great to have. I'd ideally like to design a format where it's easy to add examples for multiple languages, however. We can probably add language-specific ones for the time being but I'd prefer to not go too far down that route and ensure parity amongst the generators over time.

**Comment by nitishm** [comment]
I just realized @saona-raimundo provided a link to a repo where he has the complete example. @saona-raimundo would you want to check this in or if you want I can add it to the repo.

**Comment by saona-raimundo** [comment]
Sorry for the late reply! I am happy to add it as an example. I will do a PR for adding it in the wit-bindgen-wasmtime crate.

**Comment by radu-matei** [comment]
Just for future reference, there are a few examples for implementing and using Wasmtime host implementations in Rust in this repo, in case they are helpful to people getting started with this — https://github.com/fermyon/wasi-experimental-toolkit
