### ISSUE TITLE
funcref Support

### ISSUE THREAD

**Issue by theduke** [bytecodealliance/witx-bindgen#80]
It seems like right now there is no support for function references, is this correct?

An example where I would need this is an API for http servers:

(simplifiied)

```
type handler = function(request: request) -> expected<response, error>

resource server_manager {
  launch: function(interface: string, port: u16, handler: handler)
}
```

The idea is to pass a `server_manager` to the wasm module, which can then call `launch` with interface/port and a function pointer that can be called by the host for serving requests.

I realize there are other ways to implement this specific case, but support for passing `funcref` s would be helpful in a lot of situations.

**Comment by alexcrichton** [comment]
Indeed yeah at this time there's no support for function references. This is something that would need to be added to interface-types itself first, though, so if you're interested in pursuing this I'd recommend opening an issue over there. Otherwise though I'm going to close this since functions-as-values aren't part of the interface-types proposal at this time (which witx targets)

**Comment by theduke** [comment]
Understood, I'll propose it there.
